	units metal
	atom_style full
	pair_style reax/c NULL
    # -- Default styles (for solo "SPCE" water) --
    units        real
    atom_style   full
    # (Hybrid force fields were not necessary but are used for portability.)
    pair_style   hybrid lj/cut/coul/long 9.0
    bond_style   hybrid harmonic
    angle_style  hybrid harmonic
    kspace_style pppm 0.0001
    #pair_modify  mix arithmetic  # LEAVE THIS UNSPECIFIED!
